#### 数据的导入与导出

##### 1.提供了data数据，直接在外部复制到该工程文件下
###### .csv文件格式:可以用excel打开的表格文件
##### 2.导入后，进行了修改需要再到导出

In [20]:
import pandas as pd
import numpy as np

####  pd.read_导入的数据文件类型  导入的是.csv文件类型
df=pd.read_csv("data/employees.csv") #data是与该文件在同一目录下的文件夹
display(df)
print(df.shape)

####  df.to_导出数据文件类型  导出的是.csv文件类型
df2=df.tail(10)
df2.to_csv("data/New_employees.csv") #导出到New_employees.csv，在data文件夹下会自动创建

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

(107, 10)

#### .json数据：后端和爬虫数据传输常用格式 例左侧：test.json
###### users:是字典中的键，后面的[]是值,里面放各个用户
###### 每一个{}代表一个用户，里面的键值对代表用户的属性
###### 类似java中的ArrayList<usre> users=new ArrayList<>() users是集合名字，user是集合里面元素的类型
#### json就是字典嵌套字典
###### {"users":[]}  json本就是一个字典，users是字典中的键，后面的[]是值,里面放各个用户
###### ["{...}","{...}"]  列表中元素又是一个字典,即每一个用户,里面的键值对代表用户的属性

In [31]:
#发现结果不如预期，没有把属性name,age,salary等都显示成列名，而是作为了字典的键值对
df=pd.read_json("data/test.json")
display(df)

#改进
import json #导入json库：一个可以处理json格式数据的库。
#with open:打开文件，encoding="utf-8"是编码格式不加名字会乱码
with open("data/test.json",encoding="utf-8") as f:
    data=json.load(f)

#用json.load(f)读取文件，返回的是一个字典{"users":[]}
#data["users"],取字典中的键users对应的值，也就是后面的[]数据本身
#所以data["users"]结果就是一个列表["{...}","{...}"],列表中元素又是一个字典

df1=pd.DataFrame(data["users"]) #用单字典方式创建DataFrame
display(df1)

                                               users
0  {'id': 1, 'name': '张三', 'age': 28, 'email': 'z...
1  {'id': 2, 'name': '李四', 'age': 35, 'email': 'l...
2  {'id': 3, 'name': '王五', 'age': 24, 'email': 'w...

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20